# AcmeDemoBundle routes (to be removed)
_demo:
    resource: "@AcmeDemoBundle/Resources/config/routing.yml"
    prefix: /demo

_cmf_create:
    resource: "@CmfCreateBundle/Resources/config/routing/rest.xml"

admin:
    resource: '@SonataAdminBundle/Resources/config/routing/sonata_admin.xml'
    prefix: /admin

_sonata_admin:
    resource: .
    type: sonata_admin
    prefix: /admin

cmf_tree:
    resource: .
    type: 'cmf_tree'

fos_js_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"